In [1]:
import torch

In [2]:
a = [torch.randint(5, 3)]

TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int

In [56]:
a = [torch.randint(100, (3,)) for _ in range(4)]

In [182]:
a

[tensor([61, 32, 95]),
 tensor([46, 58, 30]),
 tensor([12, 53, 90]),
 tensor([39, 95, 71])]

In [183]:
b = torch.stack(a, dim=1)
b, b.shape

(tensor([[61, 46, 12, 39],
         [32, 58, 53, 95],
         [95, 30, 90, 71]]),
 torch.Size([3, 4]))

In [194]:
v, idx = torch.topk(b, 3, dim=1)

In [197]:
torch.gather(b, 1, idx)

tensor([[61, 46, 39],
        [95, 58, 53],
        [95, 90, 71]])

In [195]:
v

tensor([[61, 46, 39],
        [95, 58, 53],
        [95, 90, 71]])

In [196]:
idx

tensor([[0, 1, 3],
        [3, 1, 2],
        [0, 2, 3]])

In [62]:
v[:, 1]

tensor([46, 58, 90])

In [63]:
new_a = v.T
new_a

tensor([[61, 95, 95],
        [46, 58, 90]])

In [179]:
list(new_a)

[tensor([61, 95, 95]), tensor([46, 58, 90])]

In [90]:
seq_origin = [torch.arange(3*5*i, 3*5*i+3*5).view(3, 5) for i in range(4)]
seq_origin, seq_origin[0].shape

([tensor([[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14]]),
  tensor([[15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]]),
  tensor([[30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44]]),
  tensor([[45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]])],
 torch.Size([3, 5]))

In [66]:
cat_seq = torch.stack(seq_origin, dim=1)
cat_seq, cat_seq.shape

(tensor([[[ 0,  1,  2,  3,  4],
          [15, 16, 17, 18, 19],
          [30, 31, 32, 33, 34],
          [45, 46, 47, 48, 49]],
 
         [[ 5,  6,  7,  8,  9],
          [20, 21, 22, 23, 24],
          [35, 36, 37, 38, 39],
          [50, 51, 52, 53, 54]],
 
         [[10, 11, 12, 13, 14],
          [25, 26, 27, 28, 29],
          [40, 41, 42, 43, 44],
          [55, 56, 57, 58, 59]]]),
 torch.Size([3, 4, 5]))

In [75]:
idx, idx.shape

(tensor([[0, 1],
         [3, 1],
         [0, 2]]),
 torch.Size([3, 2]))

In [81]:
bidx = idx.unsqueeze(-1).expand(-1, -1, 5)

In [98]:
new_seq = torch.gather(cat_seq, 1, bidx)
new_seq = [new_seq[:, i] for i in range(new_seq.size(1))]
new_seq

[tensor([[ 0,  1,  2,  3,  4],
         [50, 51, 52, 53, 54],
         [10, 11, 12, 13, 14]]),
 tensor([[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]])]

In [153]:
features

[[tensor([[[ 0,  1],
           [ 2,  3],
           [ 4,  5],
           [ 6,  7],
           [ 8,  9]],
  
          [[10, 11],
           [12, 13],
           [14, 15],
           [16, 17],
           [18, 19]],
  
          [[20, 21],
           [22, 23],
           [24, 25],
           [26, 27],
           [28, 29]]]),
  tensor([[[ 1,  2],
           [ 3,  4],
           [ 5,  6],
           [ 7,  8],
           [ 9, 10]],
  
          [[11, 12],
           [13, 14],
           [15, 16],
           [17, 18],
           [19, 20]],
  
          [[21, 22],
           [23, 24],
           [25, 26],
           [27, 28],
           [29, 30]]]),
  tensor([[[ 2,  3],
           [ 4,  5],
           [ 6,  7],
           [ 8,  9],
           [10, 11]],
  
          [[12, 13],
           [14, 15],
           [16, 17],
           [18, 19],
           [20, 21]],
  
          [[22, 23],
           [24, 25],
           [26, 27],
           [28, 29],
           [30, 31]]])],
 [tensor([[[ 4,  5],


In [147]:
features = [[(torch.arange(3*5*2) + (i + 4*j)).view(3, 5, 2) for i in range(3)] for j in range(4)]

In [148]:
blsd = [torch.stack(x, 1) for x in features] # Batch, Layers, Seq, Dim
bclsd = torch.stack(blsd, 1) # Batch, Candidates, Layers, Seq, Dim

In [149]:
bidx = idx.reshape(3, 2, 1, 1, 1).expand(-1, -1, 3, 5, 2)

In [166]:
idx, idx.shape

(tensor([[0, 1],
         [3, 1],
         [0, 2]]),
 torch.Size([3, 2]))

In [163]:
new_features = torch.gather(bclsd, 1, bidx) # Batch, Candidates, Layers, Seq, Dim
new_features = [[new_features[:, j, i] for i in range(3)] for j in range(2)]
# new_features

In [169]:
pos_encoded = [torch.arange(3*5*2).reshape(3, 5, 2) + 3*5*2*i for i in range(4)]

In [176]:
pos_encoded

[tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7],
          [ 8,  9]],
 
         [[10, 11],
          [12, 13],
          [14, 15],
          [16, 17],
          [18, 19]],
 
         [[20, 21],
          [22, 23],
          [24, 25],
          [26, 27],
          [28, 29]]]),
 tensor([[[30, 31],
          [32, 33],
          [34, 35],
          [36, 37],
          [38, 39]],
 
         [[40, 41],
          [42, 43],
          [44, 45],
          [46, 47],
          [48, 49]],
 
         [[50, 51],
          [52, 53],
          [54, 55],
          [56, 57],
          [58, 59]]]),
 tensor([[[60, 61],
          [62, 63],
          [64, 65],
          [66, 67],
          [68, 69]],
 
         [[70, 71],
          [72, 73],
          [74, 75],
          [76, 77],
          [78, 79]],
 
         [[80, 81],
          [82, 83],
          [84, 85],
          [86, 87],
          [88, 89]]]),
 tensor([[[ 90,  91],
          [ 92,  93],
          [ 94,  95],
       

In [170]:
cat_encoded = torch.stack(pos_encoded, dim=1)
cat_encoded.shape

torch.Size([3, 4, 5, 2])

In [171]:
bidx = idx.reshape(3, 2, 1, 1).expand(-1, -1, 5, 2)

In [175]:
new_encoded = torch.gather(cat_encoded, 1, bidx)
[new_encoded[:, i] for i in range(2)]

[tensor([[[  0,   1],
          [  2,   3],
          [  4,   5],
          [  6,   7],
          [  8,   9]],
 
         [[100, 101],
          [102, 103],
          [104, 105],
          [106, 107],
          [108, 109]],
 
         [[ 20,  21],
          [ 22,  23],
          [ 24,  25],
          [ 26,  27],
          [ 28,  29]]]),
 tensor([[[30, 31],
          [32, 33],
          [34, 35],
          [36, 37],
          [38, 39]],
 
         [[40, 41],
          [42, 43],
          [44, 45],
          [46, 47],
          [48, 49]],
 
         [[80, 81],
          [82, 83],
          [84, 85],
          [86, 87],
          [88, 89]]])]